name: Stale PR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write

jobs:
  stale-pr-cleanup:
    uses: Alfresco/alfresco-build-tools/.github/workflows/stale-pr-cleanup.yml@6d82a126f5f8b2cbfe2663c2c6c4fa3dbd5bdc7e # v18.15.0
