name: Stale PR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write

jobs:
  stale-pr-cleanup:
    uses: Alfresco/alfresco-build-tools/.github/workflows/stale-pr-cleanup.yml@da0f0128094eb1e0c241cc6fda959b02594a9c8f # v18.10.0
